name: 'Dependency Review - Edge Cases and Advanced Config'

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  # Test with critical severity only
  critical-only:
    runs-on: ubuntu-latest
    name: 'Critical Vulnerabilities Only'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review - Critical Only'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          comment-summary-in-pr: on-failure
  
  # Test with specific scopes
  specific-scopes:
    runs-on: ubuntu-latest
    name: 'Test Specific Dependency Scopes'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review - Runtime Only'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-scopes: runtime
          comment-summary-in-pr: always
  
  # Test with external config file
  external-config:
    runs-on: ubuntu-latest
    name: 'Test External Config File'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review - External Config'
        uses: actions/dependency-review-action@v4
        with:
          # This would use a config file if present
          config-file: '.github/dependency-review-config.yml'
          comment-summary-in-pr: always
        continue-on-error: true
  
  # Test with custom base and head refs
  custom-refs:
    runs-on: ubuntu-latest
    name: 'Test Custom Base/Head Refs'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: 'Dependency Review - Custom Refs'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ github.event.pull_request.base.sha || github.event.before }}
          head-ref: ${{ github.event.pull_request.head.sha || github.event.after }}
          comment-summary-in-pr: always
        continue-on-error: true
  
  # Test with license allow-list and vulnerability check
  strict-security-and-licenses:
    runs-on: ubuntu-latest
    name: 'Strict Security + License Check'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review - Strict Checks'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: low
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause
          comment-summary-in-pr: always
          retry-on-snapshot-warnings: true
  
  # Test with multiple excluded packages
  exclude-packages:
    runs-on: ubuntu-latest
    name: 'Test Package Exclusions'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review - Exclude Packages'
        uses: actions/dependency-review-action@v4
        with:
          # Exclude development tools and test packages
          deny-packages: |
            pkg:npm/test-package@*
            pkg:pypi/dev-tool@*
          comment-summary-in-pr: always
        continue-on-error: true
