name: 'Test - Actions Vulnerability Scanning'

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-marketplace-actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 'Cache Dependencies'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: 'Upload Artifact Example'
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: README.md
      
      - name: 'Run a test action'
        run: echo "Testing various marketplace actions for vulnerability scanning"
